server:
  host: "0.0.0.0"
  port: 8080
  log_level: "info"
jwt:
  secret_key: "DE9981D90D3F0923F06F5C69B2273CA83BEFB95271DA134DF1C64A58AE766B42"
  algorithm: "HS256"
  access_token_expiry_seconds: 600
  refresh_token_expiry_seconds: 1500
  scopes:
    view: "Permitted to read info"
    edit: "Privileged to edit info"
    admin: "Super User"
csrf:
  secret_key: "F62858DCE32A4652A7CB32DDB1C422B00520D539A76D8E1F53E81FD351F21842"
db:
  server: "db4free.net"
  user: "fiverr_admin"
  password: "Password4Demo"
  database: "fiverr_users"
  table: "users_dev"
logs:
  level: "INFO"
